#!/bin/bash
path_to_uv=$(command -v uv)
if [ -x "$path_to_uv" ] ; then
	PYTHONHASHSEED=0 PYTHONSTARTUP=main.py uv run ipython
else
	ELDROW_SINGLETHREADED=1 ELDROW_SLOW=1 PYTHONHASHSEED=0 PYTHONSTARTUP=main.py ipython
fi
